// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelDomain model domain
// swagger:model model.Domain
type ModelDomain struct {

	// account
	Account string `json:"account,omitempty"`

	// db
	Db string `json:"db,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// last check
	LastCheck int64 `json:"last_check,omitempty"`

	// master
	Master string `json:"master,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// notified serial
	NotifiedSerial int64 `json:"notified_serial,omitempty"`

	// records
	Records ModelRecords `json:"records,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this model domain
func (m *ModelDomain) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecords(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelDomain) validateRecords(formats strfmt.Registry) error {

	if swag.IsZero(m.Records) { // not required
		return nil
	}

	if err := m.Records.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("records")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelDomain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelDomain) UnmarshalBinary(b []byte) error {
	var res ModelDomain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
