// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ModelRecord model record
// swagger:model model.Record
type ModelRecord struct {

	// auth
	Auth bool `json:"auth,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// db
	Db string `json:"db,omitempty"`

	// disabled
	Disabled bool `json:"disabled,omitempty"`

	// domain id
	DomainID int64 `json:"domain_id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// older name
	OlderName string `json:"oldername,omitempty"`

	// prio
	Prio int64 `json:"prio,omitempty"`

	// ttl
	TTL int64 `json:"ttl,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this model record
func (m *ModelRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelRecord) UnmarshalBinary(b []byte) error {
	var res ModelRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
